# Generated by Django 4.2.1 on 2023-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_product_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdf'),
            preserve_default=False,
        ),
    ]
